### ISSUE TITLE
Mac M1 arm64

### ISSUE THREAD

**Issue by diliworld** [henrhie/Note.js#4]
Mac M1 arm64

```
Error: 
You installed esbuild on another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "esbuild-darwin-64" package is present but this platform
needs the "esbuild-darwin-arm64" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead which has built-in support for installing a package on multiple
platforms simultaneously.
```

**Comment by yilmazdurmaz** [comment]
hi @diliworld 
this should already be on VSCode's extensions page, but seem something off.

can you please try to download/install [darwin-arm64](https://github.com/henrhie/Note.js/suites/5527832389/artifacts/177544013) version manually from [engine versions](https://github.com/henrhie/Note.js/actions/runs/1930593080) page?

it is possible the wrong package was uploaded under arm64 name, or the build machine gave something different than expected.

@henrhie , is this upload process also be automated by actions?

**Comment by henrhie** [comment]
@yilmazdurmaz  @diliworld Previously I was publishing manually so I might have missed the darwin-arm64 package. Currently, publishing is now automated. @diliworld Can you confirm that the error no longer appears

**Comment by diliworld** [comment]
v0.0.23
```
Error: The service is no longer running
    at /Users/xx/.vscode/extensions/henryansah.notejs-0.0.23/node_modules/esbuild/lib/main.js:1301:25
    at sendRequest (/Users/xx/.vscode/extensions/henryansah.notejs-0.0.23/node_modules/esbuild/lib/main.js:633:14)
    at buildOrServeContinue (/Users/xx/.vscode/extensions/henryansah.notejs-0.0.23/node_modules/esbuild/lib/main.js:1299:5)
    at /Users/xx/.vscode/extensions/henryansah.notejs-0.0.23/node_modules/esbuild/lib/main.js:1113:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by yilmazdurmaz** [comment]
@henrhie, It seems manually including arm64 binaries in the package is not enough as I had a similar error while trying that. "npm/yarn install" seems to do some extra processing to connect binaries.

@diliworld  It seems it will take some time to have a permanent solution. for now, you may try these two steps I had in [anohter issue](https://github.com/henrhie/Note.js/issues/1#issuecomment-1058260870). The OP confirmed this way works.
> 
> btw, if you have node.js installed, you may try this (assuming you use mac):
> 
> * check `~/. vscode/extensions` folder. if it does not exists check the internet to find where VSCode stores data in your mac.
> * open terminal in "henryansah.notejs-0.0.19" (replace version number if different)  and try "npm install esbuild-darwin-arm64"
> 

PS: I remember writing this yesterday but I guess I forgot to press the comment button below.

**Comment by henrhie** [comment]
@yilmazdurmaz I guess the temporary workaround is the solution you provided. It turns out almost all the CI/CD companies do not yet have support for apple silicon

**Comment by henrhie** [comment]
The same thing applies to the arm64 version for other operating systems. According to the Action logs, an x64 machine is used hence esbuild x64 binaries are installed.

**Comment by diliworld** [comment]
notwork

**Comment by stephen7812** [comment]
需要这个文件：downloaded-esbuild-darwin-64-esbuild 可执行文件
esbuild/lib/downloaded-esbuild-darwin-64-esbuild 
加了这个文件就正常了。
3天前我安装还可以的。后来npm install 就不行了，再也没有出现过downloaded-esbuild-darwin-64-esbuild这个文件
如果你需要，我回复邮箱，我可以发给你。文件大小 8.5MB

**Comment by henrhie** [comment]
> 需要这个文件：downloaded-esbuild-darwin-64-esbuild 可执行文件 esbuild/lib/downloaded-esbuild-darwin-64-esbuild 加了这个文件就正常了。 3天前我安装还可以的。后来npm install 就不行了，再也没有出现过downloaded-esbuild-darwin-64-esbuild这个文件 如果你需要，我回复邮箱，我可以发给你。文件大小 8.5MB

Hi @stephen7812 Could you please add an english translation for your comment
